import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "surface-container": "#e9edff",
        "background": "#f9f9ff",
        "secondary-fixed": "#acedff",
        "on-tertiary-fixed": "#351000",
        "on-surface-variant": "#464555",
        "outline": "#777587",
        "surface-container-high": "#e1e8fd",
        "primary-fixed": "#e2dfff",
        "surface": "#f9f9ff",
        "surface-container-highest": "#dce2f7",
        "tertiary-fixed-dim": "#ffb695",
        "primary-fixed-dim": "#c3c0ff",
        "surface-dim": "#d3daef",
        "on-tertiary-fixed-variant": "#7b2f00",
        "on-tertiary-container": "#ffd2be",
        "on-primary-fixed-variant": "#3323cc",
        "on-secondary-fixed-variant": "#004e5c",
        "secondary-fixed-dim": "#4cd7f6",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#c3c0ff",
        "surface-bright": "#f9f9ff",
        "on-secondary-fixed": "#001f26",
        "surface-tint": "#4d44e3",
        "secondary-container": "#57dffe",
        "error": "#ba1a1a",
        "tertiary-fixed": "#ffdbcc",
        "on-background": "#141b2b",
        "surface-container-low": "#f1f3ff",
        "primary-container": "#4f46e5",
        "inverse-on-surface": "#edf0ff",
        "tertiary-container": "#a44100",
        "surface-variant": "#dce2f7",
        "on-surface": "#141b2b",
        "tertiary": "#7e3000",
        "on-error-container": "#93000a",
        "outline-variant": "#c7c4d8",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "secondary": "#00687a",
        "on-primary-container": "#dad7ff",
        "primary": "#3525cd",
        "error-container": "#ffdad6",
        "on-secondary-container": "#006172",
        "inverse-surface": "#293040",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#0f0069",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      backgroundImage: {
        "gradient-primary": "linear-gradient(135deg, #3525cd, #4f46e5)",
      },
    },
  },
  plugins: [],
};

export default config;
